name: Moderate

on:
  schedule:
    - cron: '0 4-15 * * *'
  workflow_dispatch:

jobs:
  moderate:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container: ghcr.io/aniruth-raman/reddit-llm-moderator/reddit-moderator:latest
    steps:
      - name: Create rules.yml from secret
        run: echo "${{ secrets.RULES_YAML }}" > /app/rules.yml

      - name: Create config.yml from secret
        run: echo "${{ secrets.CONFIG_YAML }}" > /app/config.yml

      - name: Run moderation
        run: python main.py