name: Moderate

on:
  schedule:
    - cron: '0 4-15 * * *'
  workflow_dispatch:

jobs:
  moderate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aniruth-raman/reddit-llm-moderator/reddit-moderator:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: read
    steps:
      - name: Create config files from secrets
        env:
          CONFIG_YAML: ${{ secrets.CONFIG }}
          RULES_YAML: ${{ secrets.RULES }}
        run: |
          echo "$CONFIG_YAML" > config.yaml
          echo "$RULES_YAML" > rules.yaml
      - name: Run moderation
        run: python /app/main.py