name: Moderate

on:
  schedule:
    - cron: '0 4-15 * * *'
  workflow_dispatch:

jobs:
  moderate:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Create rules.yaml from secret
        run: echo "${{ secrets.RULES_YAML }}" > rules.yaml

      - name: Create config.yaml from secret
        run: echo "${{ secrets.CONFIG_YAML }}" > config.yaml

      - name: Pull Docker image
        run: docker pull ghcr.io/aniruth-raman/reddit-llm-moderator/reddit-moderator:latest

      - name: Run moderation
        run: docker run --rm -v $(pwd)/rules.yaml:/app/rules.yaml -v $(pwd)/config.yaml:/app/config.yaml ghcr.io/aniruth-raman/reddit-llm-moderator/reddit-moderator:latest